services:
  - type: web
    name: sentisensei-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask-api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0 